version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
